---
- name: Message
  ansible.builtin.debug:
    msg: Ansible role ludus-install-spice

- name: Gather facts if needed
  ansible.builtin.setup:
  when: ansible_os_family is not defined

- name: Check for Windows
  ansible.builtin.fail:
    msg: This role only supports Windows
  when: ansible_os_family != "Windows"

- name: Spice Guest agent install
  ansible.builtin.include_tasks:
    file: install_spice_guest_agent.yml
  when: ansible_os_family == "Windows"

- name: Spice Usb redirect plugin install
  ansible.builtin.include_tasks:
    file: install_spice_usb_redirect.yml
  when: ansible_os_family == "Windows" and spice_usb == true

- name: Spice Webdav folder share plugin install
  ansible.builtin.include_tasks:
    file: install_spice_webdav.yml
  when: ansible_os_family == "Windows" and spice_share == true

# Sound card cannot be added to VM with Ansible until the Feature Pull request
# https://github.com/ansible-collections/community.general/pull/9847
# Ansible log : FAILED! => {"changed": false, "msg": "Unsupported parameters for (community.general.proxmox_kvm) module: audio. Supported parameters include: acpi, agent, api_host, api_password, api_port, api_token_id, api_token_secret, api_user, archive, args, autostart, balloon, bios, boot, bootdisk, cicustom, cipassword, citype, ciupgrade, ciuser, clone, cores, cpu, cpulimit, cpuunits, delete, description, digest, efidisk0, force, format, freeze, full, hookscript, hostpci, hotplug, hugepages, ide, ipconfig, keyboard, kvm, localtime, lock, machine, memory, migrate, migrate_downtime, migrate_speed, name, nameservers, net, newid, node, numa, numa_enabled, onboot, ostype, parallel, pool, protection, reboot, revert, sata, scsi, scsihw, searchdomains, serial, shares, skiplock, smbios, snapname, sockets, sshkeys, startdate, startup, state, storage, tablet, tags, target, tdf, template, timeout, tpmstate0, update, update_unsafe, usb, validate_certs, vcpus, vga, virtio, vmid, watchdog."}
# - name: Spice sound redirection
#   ansible.builtin.include_tasks:
#     file: add_spice_sound.yml
#   when: ansible_os_family == "Windows" and spice_sound == true

- name: Spice device installation stop and start
  ansible.builtin.include_tasks:
    file: stop_start_vm.yml
  when: ansible_os_family == "Windows"
  