---
- name: Stop VM
  community.general.proxmox_kvm:
    api_user: "{{ hostvars['localhost']['api_user'] }}"
    api_password: "{{ hostvars['localhost']['api_password'] }}"
    api_host: "{{ hostvars['localhost']['api_host'] }}"
    node: "{{ hostvars['localhost']['node_name'] }}"
    vmid: "{{ proxmox_vmid }}"
    state: "stopped"
    force: true
    timeout: 30
  retries: 3
  delay: 5
  timeout: 60
  delegate_to: localhost

- name: Start VM
  community.general.proxmox_kvm:
    api_user: "{{ hostvars['localhost']['api_user'] }}"
    api_password: "{{ hostvars['localhost']['api_password'] }}"
    api_host: "{{ hostvars['localhost']['api_host'] }}"
    node: "{{ hostvars['localhost']['node_name'] }}"
    vmid: "{{ proxmox_vmid }}"
    state: "started"
    force: true
    timeout: 30
  retries: 3
  delay: 5
  timeout: 60
  delegate_to: localhost

